### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by nixfreak** [ThomasTJdev/nim_webframework#4]
Is this project still live ? I am looking for something other then Jester.

**Comment by ThomasTJdev** [comment]
Hi @nixfreak. This is just a simple framework for you to work on. The principles used are the same as in NimWC. This git only uses jester - otherwise you have to change all the route logic, which is jester-based. May I ask what your purpose/goal is?

**Comment by nixfreak** [comment]
I would like to create a dynamic website using nim to learn more and if possible e-commerce

**Comment by ThomasTJdev** [comment]
In that case you can take a look at this [this blogpost](https://ttj.dk/blog/2019/01/20/setup-a-website-with-nim), which goes through the design of a website.

I'am currently looking into an e-commerce plugin to [NimWC](https://github.com/ThomasTJdev/nim_websitecreator), but I'm still in the research phase regarding payment options/integrations. So I would advise to create a NimWC plugin 😉

**Comment by ThomasTJdev** [comment]
Closing. If you still have questions, please reopen.
